name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build:prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
        app-name: nurse-ovsm
      env:
        FIREBASE_TOKEN: AIzaSyCOnQJcLwUM1pudXx45RgYH3sVIYNLM4jA
